- model_id: "danhtran2mind/Ghibli-Stable-Diffusion-2.1-LoRA"
  local_dir: "ckpts/Ghibli-Stable-Diffusion-2.1-LoRA"
  pretrain_model_id: "stabilityai/stable-diffusion-2-1"
  base_model_id: "stabilityai/stable-diffusion-2-1"
  type: "lora"
  platform: "HuggingFace"

- model_id: "danhtran2mind/Ghibli-Stable-Diffusion-2.1-Base-finetuning"
  local_dir: "ckpts/Ghibli-Stable-Diffusion-2.1-Base-finetuning"
  pretrain_model_id: "stabilityai/stable-diffusion-2-1-base"
  type: "full_finetuning"
  platform: "HuggingFace"

- model_id: "stabilityai/stable-diffusion-2-1"
  local_dir: "ckpts/stable-diffusion-2-1"
  type: "base"
  platform: "HuggingFace"
  no_download_path:
    - "v2-1_768-ema-pruned.ckpt"
    - "v2-1_768-ema-pruned.safetensors"
    - "v2-1_768-nonema-pruned.ckpt"
    - "v2-1_768-nonema-pruned.safetensors"